<?php
/** @var stdClass $elemento */ 
/** @var String $ref */ 
?>


    <div class="card">
        <img src="<?= BASE_URL ?>imagenes/<?= $elemento->imagen ?? 'errores/imgSinCargar.png' ?>"
            class="card-img-top" alt="...">
        <div class="card-body">
            <a href="<?= BASE_URL . $this->ref . '/' . $elemento->id ?>" style="color: white"><h5 class="card-title"><?= htmlspecialchars($elemento->nombre ?? '') ?></h5></a>
        </div>
    </div>
