<?php
/** @var stdClass $elemento 
 *  @var stdClass $editor
 *  @var String $ref
 * */ 
?>


<div class="card mb-3">
    <img src="<?= BASE_URL ?>imagenes/<?= $elemento->imagen ?? 'errores/imgSinCargar.png' ?>"
        class="card-img-top " alt="...">

    <ul class="list-group list-group-flush">
        <li class="list-group-item"><?= htmlspecialchars($elemento->titulo ?? '') ?></li>
        <li class="list-group-item"><?= htmlspecialchars($elemento->descripcion ?? '') ?></li>
        <li class="list-group-item">
        <a href="<?= BASE_URL ?>editor/<?= $elemento->id_editor ?>" style="color: white">
            <?=($this->ref == 'game') ? htmlspecialchars($elemento->nombre_empresa ?? '') : htmlspecialchars($editor->nombre_empresa ?? '') ?>
        </a>    
    </li>
    </ul>
    <div class="card-body">
        <a href="<?= BASE_URL ?>game/<?= $elemento->id_juego ?>" class="card-link">Detalles</a>

    </div>
    <div class="card-footer text-muted">
        <?= $elemento->precio ?>
    </div>
</div>