                </main>
                <footer class="bg-<?= ($this->ref != 'admin') ? 'dark' : 'ligth' ?> text-ligth ">
                        <div class="text-center pt-3 pb-3">
                                <p class="mb-0">&copy; <?= date('Y') ?> STEAM - Todos los derechos reservados</p>
                        </div>
                </footer>
                <script src="<?= BASE_URL ?>/js/bootstrap.bundle.min.js"></script>
                <?php if ($this->ref == 'admin'): ?>
                        <script>
                                const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
                                const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl))
                        </script>
                <?php endif; ?>
                </body>

                </html>