                </main>
                <script src="./js/bootstrap.bundle.min.js"></script>
                <footer class="bg-<?= ($this->ref != 'admin') ? 'dark': 'ligth' ?> text-ligth ">
                        <div class="text-center pt-3 mt-3 pb-3 mt-3">
                                <p class="mb-0">&copy; 2026 STEAM - Todos los derechos reservados</p>
                        </div>
                </footer>
        </body>

</html>