<a href="<?= BASE_URL . 'home' ?>" class="btn btn-primary row col-1 m-3">Volver</a>
<form class="form-load" action="load" method="post">
    <h1 style="text-align: center;">ADMIN LOGIN</h1>
    <div class="form-floating mb-3 w-100">
        <input type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com">
        <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating w-100">
        <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
        <label for="floatingPassword">Password</label>
    </div>
    <button type="submit" class="btn btn-primary w-100">Submit</button>

</form>