<?php

/** @var String $admin
 *  @var stdclass $admin
 */
?>

<header>
    <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
        <div class="container-fluid me-5 ms-5">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-steam"
                viewBox="0 0 16 16">
                <path
                    d="M.329 10.333A8.01 8.01 0 0 0 7.99 16C12.414 16 16 12.418 16 8s-3.586-8-8.009-8A8.006 8.006 0 0 0 0 7.468l.003.006 4.304 1.769A2.2 2.2 0 0 1 5.62 8.88l1.96-2.844-.001-.04a3.046 3.046 0 0 1 3.042-3.043 3.046 3.046 0 0 1 3.042 3.043 3.047 3.047 0 0 1-3.111 3.044l-2.804 2a2.223 2.223 0 0 1-3.075 2.11 2.22 2.22 0 0 1-1.312-1.568L.33 10.333Z" />
                <path
                    d="M4.868 12.683a1.715 1.715 0 0 0 1.318-3.165 1.7 1.7 0 0 0-1.263-.02l1.023.424a1.261 1.261 0 1 1-.97 2.33l-.99-.41a1.7 1.7 0 0 0 .882.84Zm3.726-6.687a2.03 2.03 0 0 0 2.027 2.029 2.03 2.03 0 0 0 2.027-2.029 2.03 2.03 0 0 0-2.027-2.027 2.03 2.03 0 0 0-2.027 2.027m2.03-1.527a1.524 1.524 0 1 1-.002 3.048 1.524 1.524 0 0 1 .002-3.048" />
            </svg>
            <a class="navbar-brand" <?= ($this->ref != 'admin') ? 'href="' . BASE_URL . 'home"' : 'href="' . BASE_URL . 'adminview"' ?>><?= ($this->ref === 'admin') ? ' WIKI STEAM ADMIN CONTROL' : 'WIKI STEAM' ?></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav me-auto">
                    <?php if ($this->ref != 'admin'): ?>
                        <li class="nav-item">
                            <a class="nav-link <?= ($this->ref == 'editor' || $this->ref == 'admin') ? 'active' : '' ?>" href="<?= BASE_URL ?>editors">Editores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link <?= ($this->ref == 'game' || $this->ref == 'admin') ? 'active' : '' ?>" href="<?= BASE_URL ?>games">Juegos</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link <?= ($this->ref == 'about' || $this->ref == 'admin') ? 'active' : '' ?>" href="<?= BASE_URL ?>about">About</a>
                        </li>
                        <?php if (isset($_SESSION['admin'])) : ?>
                            <li class="nav-item">
                                <a class="nav-link " href="<?= BASE_URL . 'adminview' ?>">Administrar</a>
                            </li>
                        <?php endif; ?>
                    <?php else: ?>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Editores</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="<?= BASE_URL ?>editEditores">Ediciones</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="formAltasEditores">Form altas</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Juegos</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="<?= BASE_URL ?>editGames">Ediciones</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="formAltasGames">Form altas</a>
                            </div>
                        </li>
                </ul>
                <div class="logg-out">
                    <p class="mt-1 mb-1">Hola <?= $admin->nombre_apellido ?>!</p>
                    <a href="<?= BASE_URL . 'sessionout' ?>" type="button" class="btn btn-dark">Cerrar seción
                    </a>
                </div>
            <?php endif; ?>
            </div>
        </div>
    </nav>
</header>
<main>