<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?= ($this->ref === 'admin') ? BASE_URL.'css/admin-bootstrap.min.css' : BASE_URL.'css/public-bootstrap.min.css'?>">
    <link rel="stylesheet" href="<?= BASE_URL ?>css/style.css">
    <title>WIKI STEAM</title>
</head>
<body>