<?php

/** @var stdClass $game */
?>

<section class="npe-5 ps-5">
    <h1 class="mb-4 mt-4 text-md-left"><?= htmlspecialchars($game->titulo) ?>&trade;</h1>
    <h2> <?= htmlspecialchars($game->descripcion) ?> </h2>
    <img class="noticia-image"
        src="<?= BASE_URL ?>imagenes/<?= $game->imagen ?? 'errores/imgSinCargar.png' ?>"
        alt="...">
    <div class="row align-items-start mt-5 mb-5">
        <div class="col-12 col-md-8">
            <p class="lead p-2 bg-dark" style="border: 0.1mm steelgray solid; border-radius: 5px;"><?= htmlspecialchars($game->resenia) ?></p>
        </div>
        <div class="col-12 col-md-4">
            <ul class="list-group">
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Valoracion
                    <span class="badge bg-primary rounded-pill"><?= $game->valoracion ?></span>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Fecha de lanzamiento
                    <small><?= $game->fecha_lanzamiento ?></small>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    Precio
                    <small><?= $game->precio ?></small>
                </li>
                <li class="list-group-item d-flex align-items-center text-info">
                    <a class="text-info" href="<?= BASE_URL . 'editor/' . $game->id_editor?>" style="color: white;"><?= htmlspecialchars($game->nombre_empresa) ?></a>
                </li>
            </ul>
        </div>

    </div>
</section>