<?php if (!empty($_SESSION['mensaje'])): ?>
    <div class="alert alert-<?=$_SESSION['alert_type'] ?? 'warning'?> alert-dismissible fade show" role="alert">
        
        <?= $_SESSION['mensaje'] ?>
        
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    
    <?php 
        unset($_SESSION['mensaje']); 
        unset($_SESSION['alert_type']); 
    ?>
<?php endif; ?>